# Shizukana v0.1.0

"$schema" = 'https://starship.rs/config-schema.json'

format = """
[░▒▓](color_red)\
$os\
$username\
[](bg:color_cyan fg:color_red)\
$directory\
[](fg:color_cyan bg:color_orange)\
$git_branch\
$git_status\
[](fg:color_orange bg:color_yellow)\
$c\
$cpp\
$rust\
$kotlin\
$haskell\
[](fg:color_yellow bg:color_blue)\
$php\
$java\
$golang\
[](fg:color_blue bg:color_green)\
$nodejs\
$python\
[](fg:color_green bg:color_bg3)\
$docker_context\
$conda\
$pixi\
[](fg:color_bg3 bg:color_bg1)\
$time\
[▓▒░ ](fg:color_bg1)\
$line_break$character"""

palette = 'shizukana'

[palettes.shizukana]
# Main colors for the theme
color_fg0 = '#cae6f0' # main text
color_fg1 = '#cbb3c6' # secondary text
color_bg0 = '#15121c' # darkest background
color_bg1 = '#5b6e87' # main background
color_bg2 = '#8da1a8' # medium background
color_bg3 = '#c1a4bb' # light background/borders

# Highlight colors
color_red = '#bb606e'    # red
color_green = '#639b9a'  # green  
color_yellow = '#b3a15e' # yellow/gold
color_blue = '#68b5c5'   # blue
color_purple = '#dc97ad' # purple/pink
color_cyan = '#8dc7d3'   # cyan
color_orange = '#ca848f' # orange/peach

# Bright/alternative colors
color_bright_red = '#ca848f'
color_bright_green = '#82afae'
color_bright_yellow = '#c3b581'
color_bright_blue = '#deeff6'
color_bright_purple = '#e9bdcb'
color_bright_cyan = '#cbb3c6'

# Git/Diff specific colors
color_git_add = '#639b9a'
color_git_change = '#b3a15e'
color_git_delete = '#bb606e'

# Comments and details colors
color_comment = '#8da1a8'
color_wave_blue = '#5b6e87' # popups/floats

[os]
disabled = false
style = "bg:color_red fg:color_fg0"
format = '[ $symbol]($style)'

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = true
style_user = "bg:color_red fg:color_fg0"
style_root = "bg:color_red fg:color_fg0"
format = '[ $user ]($style)'

[directory]
truncation_length = 3
truncation_symbol = "…/"
style = "fg:color_bg0 bg:color_cyan"
format = "[ $path ]($style)"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
format = '[ $symbol$branch(:$remote_branch)]($style)'
style = 'bg:color_orange fg:color_bg0'
symbol = '󰘬 '
truncation_length = 12

[git_status]
format = '[ $all_status$ahead_behind ]($style)'
style = 'bg:color_orange fg:color_bg0'

[c]
symbol = " "
style = 'bg:color_yellow fg:color_bg0'
format = '[ $symbol ($version) ]($style)'

[cpp]
symbol = " "
style = 'bg:color_yellow fg:color_bg0'
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = '󱘗'
style = 'bg:color_yellow fg:color_bg0'
format = '[ $symbol ($version) ]($style)'

[kotlin]
symbol = ""
style = 'bg:color_yellow fg:color_bg0'
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = ""
style = 'bg:color_yellow fg:color_bg0'
format = '[ $symbol ($version) ]($style)'

[php]
symbol = ''
format = '[ $symbol ($version) ]($style)'
style = 'bg:color_blue fg:color_bg0'

[java]
symbol = ""
format = '[ $symbol ($version) ]($style)'
style = 'bg:color_blue fg:color_bg0'

[golang]
symbol = ""
format = '[ $symbol ($version) ]($style)'
style = 'bg:color_blue fg:color_bg0'

[nodejs]
symbol = ""
format = '[ $symbol($version) ]($style)'
style = 'bg:color_green fg:color_fg0'
not_capable_style = 'bg:color_red fg:color_fg0'

[python]
symbol = ""
format = '[ $symbol($version) ]($style)'
style = 'bg:color_green fg:color_fg0'

[docker_context]
symbol = ""
format = '[ $symbol( $context) ]($style)'
style = 'bg:color_bg3 fg:color_bg0'

[conda]
format = '[ $symbol( $environment) ]($style)'
style = 'bg:color_bg3 fg:color_bg0'

[pixi]
format = '[ $symbol( $version)( $environment) ]($style)'
style = 'bg:color_bg3 fg:color_bg0'

[time]
disabled = false
time_format = "%R"
style = 'bg:color_wave_blue fg:color_fg0'
format = '[  $time ]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'
